[package]
name = "adventofcode2020rust"
version = "0.1.0"
authors = ["jyli <jyli@dtu.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
itertools = "*"